/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 08/10/2021 13:41:03
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            64000000
#define MX_HSE_VALUE                            24000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_SYSCLKFreq_VALUE                     280000000
#define MX_HCLKFreq_Value                       140000000
#define MX_CortexFreq_Value                     280000000
#define MX_APB1Freq_Value                       70000000
#define MX_APB2Freq_Value                       70000000
#define MX_CECFreq_Value                        32000
#define MX_RTCFreq_Value                        32768
#define MX_USBFreq_Value                        186666666
#define MX_WatchDogFreq_Value                   32000
#define MX_SPDIFRXFreq_Value                    186666666
#define MX_MCO1PinFreq_Value                    24000000
#define MX_MCO2PinFreq_Value                    280000000

/*-------------------------------- CORTEX_M7  --------------------------------*/

#define MX_CORTEX_M7                            1

/* GPIO Configuration */

/*-------------------------------- DEBUG      --------------------------------*/

#define MX_DEBUG                                1

/* GPIO Configuration */

/* Pin PA15 */
#define MX_DEBUG_JTDI_Pin                       PA15
#define MX_JTDI                                 DEBUG_JTDI

/* Pin PA14 */
#define MX_DEBUG_JTCK_SWCLK_Pin                 PA14
#define MX_JTCK                                 DEBUG_JTCK_SWCLK

/* Pin PB4 */
#define MX_DEBUG_JTRST_Pin                      PB4

/* Pin PB3 */
#define MX_DEBUG_JTDO_SWO_Pin                   PB3
#define MX_JTDO_TRACESWO                        DEBUG_JTDO_SWO

/* Pin PA13 */
#define MX_DEBUG_JTMS_SWDIO_Pin                 PA13
#define MX_JTMS                                 DEBUG_JTMS_SWDIO

/*-------------------------------- DMA        --------------------------------*/

#define MX_DMA                                  1

/* NVIC Configuration */

/* NVIC DMA1_Stream1_IRQn */
#define MX_DMA1_Stream1_IRQn_interruptPremptionPriority 8
#define MX_DMA1_Stream1_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA1_Stream1_IRQn_Subriority         0

/* NVIC DMA1_Stream0_IRQn */
#define MX_DMA1_Stream0_IRQn_interruptPremptionPriority 8
#define MX_DMA1_Stream0_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA1_Stream0_IRQn_Subriority         0

/*-------------------------------- DMA2D      --------------------------------*/

#define MX_DMA2D                                1

/* GPIO Configuration */

/*-------------------------------- FMC        --------------------------------*/

#define MX_FMC                                  1

/* GPIO Configuration */

/* Pin PE11 */
#define MX_FMC_D8_DA8_Pin                       PE11
#define MX_FMC_D8_DA8_GPIOx                     GPIOE
#define MX_FMC_D8_DA8_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D8_DA8_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_D8                                   FMC_D8_DA8
#define MX_FMC_D8_DA8_GPIO_Pin                  GPIO_PIN_11
#define MX_FMC_D8_DA8_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D8_DA8_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PH7 */
#define MX_FMC_SDCKE1_Pin                       PH7
#define MX_FMC_SDCKE1_GPIOx                     GPIOH
#define MX_FMC_SDCKE1_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_SDCKE1_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDCKE1                               FMC_SDCKE1
#define MX_FMC_SDCKE1_GPIO_Pin                  GPIO_PIN_7
#define MX_FMC_SDCKE1_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_SDCKE1_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PF0 */
#define MX_FMC_A0_Pin                           PF0
#define MX_FMC_A0_GPIOx                         GPIOF
#define MX_FMC_A0_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A0_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_A0                                   FMC_A0
#define MX_FMC_A0_GPIO_Pin                      GPIO_PIN_0
#define MX_FMC_A0_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A0_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PF1 */
#define MX_FMC_A1_Pin                           PF1
#define MX_FMC_A1_GPIOx                         GPIOF
#define MX_FMC_A1_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A1_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_A1                                   FMC_A1
#define MX_FMC_A1_GPIO_Pin                      GPIO_PIN_1
#define MX_FMC_A1_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A1_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PD1 */
#define MX_FMC_D3_DA3_Pin                       PD1
#define MX_FMC_D3_DA3_GPIOx                     GPIOD
#define MX_FMC_D3_DA3_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D3_DA3_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_D3                                   FMC_D3_DA3
#define MX_FMC_D3_DA3_GPIO_Pin                  GPIO_PIN_1
#define MX_FMC_D3_DA3_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D3_DA3_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PF2 */
#define MX_FMC_A2_Pin                           PF2
#define MX_FMC_A2_GPIOx                         GPIOF
#define MX_FMC_A2_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A2_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_A2                                   FMC_A2
#define MX_FMC_A2_GPIO_Pin                      GPIO_PIN_2
#define MX_FMC_A2_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A2_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PF11 */
#define MX_FMC_SDNRAS_Pin                       PF11
#define MX_FMC_SDNRAS_GPIOx                     GPIOF
#define MX_FMC_SDNRAS_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_SDNRAS_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDNRAS                               FMC_SDNRAS
#define MX_FMC_SDNRAS_GPIO_Pin                  GPIO_PIN_11
#define MX_FMC_SDNRAS_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_SDNRAS_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PF3 */
#define MX_FMC_A3_Pin                           PF3
#define MX_FMC_A3_GPIOx                         GPIOF
#define MX_FMC_A3_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A3_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_A3                                   FMC_A3
#define MX_FMC_A3_GPIO_Pin                      GPIO_PIN_3
#define MX_FMC_A3_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A3_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PF4 */
#define MX_FMC_A4_Pin                           PF4
#define MX_FMC_A4_GPIOx                         GPIOF
#define MX_FMC_A4_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A4_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_A4                                   FMC_A4
#define MX_FMC_A4_GPIO_Pin                      GPIO_PIN_4
#define MX_FMC_A4_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A4_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PH6 */
#define MX_FMC_SDNE1_Pin                        PH6
#define MX_FMC_SDNE1_GPIOx                      GPIOH
#define MX_FMC_SDNE1_GPIO_PuPd                  GPIO_NOPULL
#define MX_FMC_SDNE1_GPIO_Speed_High_Default    GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDNE1                                FMC_SDNE1
#define MX_FMC_SDNE1_GPIO_Pin                   GPIO_PIN_6
#define MX_FMC_SDNE1_GPIO_AF                    GPIO_AF12_FMC
#define MX_FMC_SDNE1_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PF5 */
#define MX_FMC_A5_Pin                           PF5
#define MX_FMC_A5_GPIOx                         GPIOF
#define MX_FMC_A5_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A5_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_A5                                   FMC_A5
#define MX_FMC_A5_GPIO_Pin                      GPIO_PIN_5
#define MX_FMC_A5_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A5_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PH5 */
#define MX_FMC_SDNWE_Pin                        PH5
#define MX_FMC_SDNWE_GPIOx                      GPIOH
#define MX_FMC_SDNWE_GPIO_PuPd                  GPIO_NOPULL
#define MX_FMC_SDNWE_GPIO_Speed_High_Default    GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDNWE                                FMC_SDNWE
#define MX_FMC_SDNWE_GPIO_Pin                   GPIO_PIN_5
#define MX_FMC_SDNWE_GPIO_AF                    GPIO_AF12_FMC
#define MX_FMC_SDNWE_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PF12 */
#define MX_FMC_A6_Pin                           PF12
#define MX_FMC_A6_GPIOx                         GPIOF
#define MX_FMC_A6_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A6_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_A6                                   FMC_A6
#define MX_FMC_A6_GPIO_Pin                      GPIO_PIN_12
#define MX_FMC_A6_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A6_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PG0 */
#define MX_FMC_A10_Pin                          PG0
#define MX_FMC_A10_GPIOx                        GPIOG
#define MX_FMC_A10_GPIO_PuPd                    GPIO_NOPULL
#define MX_FMC_A10_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_A10                                  FMC_A10
#define MX_FMC_A10_GPIO_Pin                     GPIO_PIN_0
#define MX_FMC_A10_GPIO_AF                      GPIO_AF12_FMC
#define MX_FMC_A10_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PF13 */
#define MX_FMC_A7_Pin                           PF13
#define MX_FMC_A7_GPIOx                         GPIOF
#define MX_FMC_A7_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A7_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_A7                                   FMC_A7
#define MX_FMC_A7_GPIO_Pin                      GPIO_PIN_13
#define MX_FMC_A7_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A7_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PD9 */
#define MX_FMC_D14_DA14_Pin                     PD9
#define MX_FMC_D14_DA14_GPIOx                   GPIOD
#define MX_FMC_D14_DA14_GPIO_PuPd               GPIO_NOPULL
#define MX_FMC_D14_DA14_GPIO_Speed_High_Default GPIO_SPEED_FREQ_VERY_HIGH
#define MX_D14                                  FMC_D14_DA14
#define MX_FMC_D14_DA14_GPIO_Pin                GPIO_PIN_9
#define MX_FMC_D14_DA14_GPIO_AF                 GPIO_AF12_FMC
#define MX_FMC_D14_DA14_GPIO_Mode               GPIO_MODE_AF_PP

/* Pin PF14 */
#define MX_FMC_A8_Pin                           PF14
#define MX_FMC_A8_GPIOx                         GPIOF
#define MX_FMC_A8_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A8_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_A8                                   FMC_A8
#define MX_FMC_A8_GPIO_Pin                      GPIO_PIN_14
#define MX_FMC_A8_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A8_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PF15 */
#define MX_FMC_A9_Pin                           PF15
#define MX_FMC_A9_GPIOx                         GPIOF
#define MX_FMC_A9_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A9_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_A9                                   FMC_A9
#define MX_FMC_A9_GPIO_Pin                      GPIO_PIN_15
#define MX_FMC_A9_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A9_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PG1 */
#define MX_FMC_A11_Pin                          PG1
#define MX_FMC_A11_GPIOx                        GPIOG
#define MX_FMC_A11_GPIO_PuPd                    GPIO_NOPULL
#define MX_FMC_A11_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_A11                                  FMC_A11
#define MX_FMC_A11_GPIO_Pin                     GPIO_PIN_1
#define MX_FMC_A11_GPIO_AF                      GPIO_AF12_FMC
#define MX_FMC_A11_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PE14 */
#define MX_FMC_D11_DA11_Pin                     PE14
#define MX_FMC_D11_DA11_GPIOx                   GPIOE
#define MX_FMC_D11_DA11_GPIO_PuPd               GPIO_NOPULL
#define MX_FMC_D11_DA11_GPIO_Speed_High_Default GPIO_SPEED_FREQ_VERY_HIGH
#define MX_D11                                  FMC_D11_DA11
#define MX_FMC_D11_DA11_GPIO_Pin                GPIO_PIN_14
#define MX_FMC_D11_DA11_GPIO_AF                 GPIO_AF12_FMC
#define MX_FMC_D11_DA11_GPIO_Mode               GPIO_MODE_AF_PP

/* Pin PE7 */
#define MX_FMC_D4_DA4_Pin                       PE7
#define MX_FMC_D4_DA4_GPIOx                     GPIOE
#define MX_FMC_D4_DA4_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D4_DA4_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_D4                                   FMC_D4_DA4
#define MX_FMC_D4_DA4_GPIO_Pin                  GPIO_PIN_7
#define MX_FMC_D4_DA4_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D4_DA4_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PE10 */
#define MX_FMC_D7_DA7_Pin                       PE10
#define MX_FMC_D7_DA7_GPIOx                     GPIOE
#define MX_FMC_D7_DA7_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D7_DA7_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_D7                                   FMC_D7_DA7
#define MX_FMC_D7_DA7_GPIO_Pin                  GPIO_PIN_10
#define MX_FMC_D7_DA7_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D7_DA7_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PG5 */
#define MX_FMC_A15_BA1_Pin                      PG5
#define MX_FMC_A15_BA1_GPIOx                    GPIOG
#define MX_FMC_A15_BA1_GPIO_PuPd                GPIO_NOPULL
#define MX_FMC_A15_BA1_GPIO_Speed_High_Default  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_A15                                  FMC_A15_BA1
#define MX_FMC_A15_BA1_GPIO_Pin                 GPIO_PIN_5
#define MX_FMC_A15_BA1_GPIO_AF                  GPIO_AF12_FMC
#define MX_FMC_A15_BA1_GPIO_Mode                GPIO_MODE_AF_PP

/* Pin PE1 */
#define MX_FMC_NBL1_Pin                         PE1
#define MX_FMC_NBL1_GPIOx                       GPIOE
#define MX_FMC_NBL1_GPIO_PuPd                   GPIO_NOPULL
#define MX_FMC_NBL1_GPIO_Speed_High_Default     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_NBL1                             FMC_NBL1
#define MX_FMC_NBL1_GPIO_Pin                    GPIO_PIN_1
#define MX_FMC_NBL1_GPIO_AF                     GPIO_AF12_FMC
#define MX_FMC_NBL1_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PE0 */
#define MX_FMC_NBL0_Pin                         PE0
#define MX_FMC_NBL0_GPIOx                       GPIOE
#define MX_FMC_NBL0_GPIO_PuPd                   GPIO_NOPULL
#define MX_FMC_NBL0_GPIO_Speed_High_Default     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_NBL0                             FMC_NBL0
#define MX_FMC_NBL0_GPIO_Pin                    GPIO_PIN_0
#define MX_FMC_NBL0_GPIO_AF                     GPIO_AF12_FMC
#define MX_FMC_NBL0_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PD14 */
#define MX_FMC_D0_DA0_Pin                       PD14
#define MX_FMC_D0_DA0_GPIOx                     GPIOD
#define MX_FMC_D0_DA0_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D0_DA0_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_D0                                   FMC_D0_DA0
#define MX_FMC_D0_DA0_GPIO_Pin                  GPIO_PIN_14
#define MX_FMC_D0_DA0_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D0_DA0_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PE13 */
#define MX_FMC_D10_DA10_Pin                     PE13
#define MX_FMC_D10_DA10_GPIOx                   GPIOE
#define MX_FMC_D10_DA10_GPIO_PuPd               GPIO_NOPULL
#define MX_FMC_D10_DA10_GPIO_Speed_High_Default GPIO_SPEED_FREQ_VERY_HIGH
#define MX_D10                                  FMC_D10_DA10
#define MX_FMC_D10_DA10_GPIO_Pin                GPIO_PIN_13
#define MX_FMC_D10_DA10_GPIO_AF                 GPIO_AF12_FMC
#define MX_FMC_D10_DA10_GPIO_Mode               GPIO_MODE_AF_PP

/* Pin PE8 */
#define MX_FMC_D5_DA5_Pin                       PE8
#define MX_FMC_D5_DA5_GPIOx                     GPIOE
#define MX_FMC_D5_DA5_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D5_DA5_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_D5                                   FMC_D5_DA5
#define MX_FMC_D5_DA5_GPIO_Pin                  GPIO_PIN_8
#define MX_FMC_D5_DA5_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D5_DA5_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PD8 */
#define MX_FMC_D13_DA13_Pin                     PD8
#define MX_FMC_D13_DA13_GPIOx                   GPIOD
#define MX_FMC_D13_DA13_GPIO_PuPd               GPIO_NOPULL
#define MX_FMC_D13_DA13_GPIO_Speed_High_Default GPIO_SPEED_FREQ_VERY_HIGH
#define MX_D13                                  FMC_D13_DA13
#define MX_FMC_D13_DA13_GPIO_Pin                GPIO_PIN_8
#define MX_FMC_D13_DA13_GPIO_AF                 GPIO_AF12_FMC
#define MX_FMC_D13_DA13_GPIO_Mode               GPIO_MODE_AF_PP

/* Pin PG4 */
#define MX_FMC_A14_BA0_Pin                      PG4
#define MX_FMC_A14_BA0_GPIOx                    GPIOG
#define MX_FMC_A14_BA0_GPIO_PuPd                GPIO_NOPULL
#define MX_FMC_A14_BA0_GPIO_Speed_High_Default  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_A14                                  FMC_A14_BA0
#define MX_FMC_A14_BA0_GPIO_Pin                 GPIO_PIN_4
#define MX_FMC_A14_BA0_GPIO_AF                  GPIO_AF12_FMC
#define MX_FMC_A14_BA0_GPIO_Mode                GPIO_MODE_AF_PP

/* Pin PG8 */
#define MX_FMC_SDCLK_Pin                        PG8
#define MX_FMC_SDCLK_GPIOx                      GPIOG
#define MX_FMC_SDCLK_GPIO_PuPd                  GPIO_NOPULL
#define MX_FMC_SDCLK_GPIO_Speed_High_Default    GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDCLK                                FMC_SDCLK
#define MX_FMC_SDCLK_GPIO_Pin                   GPIO_PIN_8
#define MX_FMC_SDCLK_GPIO_AF                    GPIO_AF12_FMC
#define MX_FMC_SDCLK_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PE15 */
#define MX_FMC_D12_DA12_Pin                     PE15
#define MX_FMC_D12_DA12_GPIOx                   GPIOE
#define MX_FMC_D12_DA12_GPIO_PuPd               GPIO_NOPULL
#define MX_FMC_D12_DA12_GPIO_Speed_High_Default GPIO_SPEED_FREQ_VERY_HIGH
#define MX_D12                                  FMC_D12_DA12
#define MX_FMC_D12_DA12_GPIO_Pin                GPIO_PIN_15
#define MX_FMC_D12_DA12_GPIO_AF                 GPIO_AF12_FMC
#define MX_FMC_D12_DA12_GPIO_Mode               GPIO_MODE_AF_PP

/* Pin PD15 */
#define MX_FMC_D1_DA1_Pin                       PD15
#define MX_FMC_D1_DA1_GPIOx                     GPIOD
#define MX_FMC_D1_DA1_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D1_DA1_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_D1                                   FMC_D1_DA1
#define MX_FMC_D1_DA1_GPIO_Pin                  GPIO_PIN_15
#define MX_FMC_D1_DA1_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D1_DA1_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PG15 */
#define MX_FMC_SDNCAS_Pin                       PG15
#define MX_FMC_SDNCAS_GPIOx                     GPIOG
#define MX_FMC_SDNCAS_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_SDNCAS_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDNCAS                               FMC_SDNCAS
#define MX_FMC_SDNCAS_GPIO_Pin                  GPIO_PIN_15
#define MX_FMC_SDNCAS_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_SDNCAS_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PE12 */
#define MX_FMC_D9_DA9_Pin                       PE12
#define MX_FMC_D9_DA9_GPIOx                     GPIOE
#define MX_FMC_D9_DA9_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D9_DA9_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_D9                                   FMC_D9_DA9
#define MX_FMC_D9_DA9_GPIO_Pin                  GPIO_PIN_12
#define MX_FMC_D9_DA9_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D9_DA9_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PD0 */
#define MX_FMC_D2_DA2_Pin                       PD0
#define MX_FMC_D2_DA2_GPIOx                     GPIOD
#define MX_FMC_D2_DA2_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D2_DA2_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_D2                                   FMC_D2_DA2
#define MX_FMC_D2_DA2_GPIO_Pin                  GPIO_PIN_0
#define MX_FMC_D2_DA2_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D2_DA2_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PE9 */
#define MX_FMC_D6_DA6_Pin                       PE9
#define MX_FMC_D6_DA6_GPIOx                     GPIOE
#define MX_FMC_D6_DA6_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D6_DA6_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_D6                                   FMC_D6_DA6
#define MX_FMC_D6_DA6_GPIO_Pin                  GPIO_PIN_9
#define MX_FMC_D6_DA6_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D6_DA6_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PD10 */
#define MX_FMC_D15_DA15_Pin                     PD10
#define MX_FMC_D15_DA15_GPIOx                   GPIOD
#define MX_FMC_D15_DA15_GPIO_PuPd               GPIO_NOPULL
#define MX_FMC_D15_DA15_GPIO_Speed_High_Default GPIO_SPEED_FREQ_VERY_HIGH
#define MX_D15                                  FMC_D15_DA15
#define MX_FMC_D15_DA15_GPIO_Pin                GPIO_PIN_10
#define MX_FMC_D15_DA15_GPIO_AF                 GPIO_AF12_FMC
#define MX_FMC_D15_DA15_GPIO_Mode               GPIO_MODE_AF_PP

/*-------------------------------- I2C4       --------------------------------*/

#define MX_I2C4                                 1

/* GPIO Configuration */

/* Pin PD13 */
#define MX_I2C4_SDA_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_I2C4_SDA_Pin                         PD13
#define MX_I2C4_SDA_GPIOx                       GPIOD
#define MX_I2C4_SDA                             I2C4_SDA
#define MX_I2C4_SDA_GPIO_Pin                    GPIO_PIN_13
#define MX_I2C4_SDA_GPIO_AF                     GPIO_AF4_I2C4
#define MX_I2C4_SDA_GPIO_Pu                     GPIO_PULLUP
#define MX_I2C4_SDA_GPIO_Mode                   GPIO_MODE_AF_OD

/* Pin PD12 */
#define MX_I2C4_SCL_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_I2C4_SCL_Pin                         PD12
#define MX_I2C4_SCL_GPIOx                       GPIOD
#define MX_I2C4_SCL                             I2C4_SCL
#define MX_I2C4_SCL_GPIO_Pin                    GPIO_PIN_12
#define MX_I2C4_SCL_GPIO_AF                     GPIO_AF4_I2C4
#define MX_I2C4_SCL_GPIO_Pu                     GPIO_PULLUP
#define MX_I2C4_SCL_GPIO_Mode                   GPIO_MODE_AF_OD

/*-------------------------------- I2S6       --------------------------------*/

#define MX_I2S6                                 1

/* GPIO Configuration */

/* Pin PG12 */
#define MX_I2S6_SDI_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_I2S6_SDI_Pin                         PG12
#define MX_I2S6_SDI_GPIOx                       GPIOG
#define MX_I2S6_SDI_GPIO_PuPd                   GPIO_NOPULL
#define MX_I2S6_SDI                             I2S6_SDI
#define MX_I2S6_SDI_GPIO_Pin                    GPIO_PIN_12
#define MX_I2S6_SDI_GPIO_AF                     GPIO_AF5_SPI6
#define MX_I2S6_SDI_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PA3 */
#define MX_I2S6_MCK_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_I2S6_MCK_Pin                         PA3
#define MX_I2S6_MCK_GPIOx                       GPIOA
#define MX_I2S6_MCK_GPIO_PuPd                   GPIO_NOPULL
#define MX_I2S6_MCK                             I2S6_MCK
#define MX_I2S6_MCK_GPIO_Pin                    GPIO_PIN_3
#define MX_I2S6_MCK_GPIO_AF                     GPIO_AF5_SPI6
#define MX_I2S6_MCK_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PA0 */
#define MX_I2S6_WS_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_I2S6_WS_Pin                          PA0
#define MX_I2S6_WS_GPIOx                        GPIOA
#define MX_I2S6_WS_GPIO_PuPd                    GPIO_NOPULL
#define MX_I2S6_WS                              I2S6_WS
#define MX_I2S6_WS_GPIO_Pin                     GPIO_PIN_0
#define MX_I2S6_WS_GPIO_AF                      GPIO_AF5_SPI6
#define MX_I2S6_WS_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PG14 */
#define MX_I2S6_SDO_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_I2S6_SDO_Pin                         PG14
#define MX_I2S6_SDO_GPIOx                       GPIOG
#define MX_I2S6_SDO_GPIO_PuPd                   GPIO_NOPULL
#define MX_I2S6_SDO                             I2S6_SDO
#define MX_I2S6_SDO_GPIO_Pin                    GPIO_PIN_14
#define MX_I2S6_SDO_GPIO_AF                     GPIO_AF5_SPI6
#define MX_I2S6_SDO_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PG13 */
#define MX_I2S6_CK_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_I2S6_CK_Pin                          PG13
#define MX_I2S6_CK_GPIOx                        GPIOG
#define MX_I2S6_CK_GPIO_PuPd                    GPIO_NOPULL
#define MX_I2S6_CK                              I2S6_CK
#define MX_I2S6_CK_GPIO_Pin                     GPIO_PIN_13
#define MX_I2S6_CK_GPIO_AF                      GPIO_AF5_SPI6
#define MX_I2S6_CK_GPIO_Mode                    GPIO_MODE_AF_PP

/*-------------------------------- LTDC       --------------------------------*/

#define MX_LTDC                                 1

/* GPIO Configuration */

/* Pin PI14 */
#define MX_LTDC_CLK_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_LTDC_CLK_Pin                         PI14
#define MX_LTDC_CLK_GPIOx                       GPIOI
#define MX_LTDC_CLK_GPIO_PuPd                   GPIO_NOPULL
#define MX_LCD_CLK                              LTDC_CLK
#define MX_LTDC_CLK_GPIO_Pin                    GPIO_PIN_14
#define MX_LTDC_CLK_GPIO_AF                     GPIO_AF14_LTDC
#define MX_LTDC_CLK_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PK2 */
#define MX_LTDC_G7_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_G7_Pin                          PK2
#define MX_LTDC_G7_GPIOx                        GPIOK
#define MX_LTDC_G7_GPIO_PuPd                    GPIO_NOPULL
#define MX_LCD_G7                               LTDC_G7
#define MX_LTDC_G7_GPIO_Pin                     GPIO_PIN_2
#define MX_LTDC_G7_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_G7_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PK0 */
#define MX_LTDC_G5_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_G5_Pin                          PK0
#define MX_LTDC_G5_GPIOx                        GPIOK
#define MX_LTDC_G5_GPIO_PuPd                    GPIO_NOPULL
#define MX_LCD_G5                               LTDC_G5
#define MX_LTDC_G5_GPIO_Pin                     GPIO_PIN_0
#define MX_LTDC_G5_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_G5_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PK1 */
#define MX_LTDC_G6_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_G6_Pin                          PK1
#define MX_LTDC_G6_GPIOx                        GPIOK
#define MX_LTDC_G6_GPIO_PuPd                    GPIO_NOPULL
#define MX_LCD_G6                               LTDC_G6
#define MX_LTDC_G6_GPIO_Pin                     GPIO_PIN_1
#define MX_LTDC_G6_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_G6_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PJ10 */
#define MX_LTDC_G3_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_G3_Pin                          PJ10
#define MX_LTDC_G3_GPIOx                        GPIOJ
#define MX_LTDC_G3_GPIO_PuPd                    GPIO_NOPULL
#define MX_LCD_G3                               LTDC_G3
#define MX_LTDC_G3_GPIO_Pin                     GPIO_PIN_10
#define MX_LTDC_G3_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_G3_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PJ11 */
#define MX_LTDC_G4_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_G4_Pin                          PJ11
#define MX_LTDC_G4_GPIOx                        GPIOJ
#define MX_LTDC_G4_GPIO_PuPd                    GPIO_NOPULL
#define MX_LCD_G4                               LTDC_G4
#define MX_LTDC_G4_GPIO_Pin                     GPIO_PIN_11
#define MX_LTDC_G4_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_G4_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PJ8 */
#define MX_LTDC_G1_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_G1_Pin                          PJ8
#define MX_LTDC_G1_GPIOx                        GPIOJ
#define MX_LTDC_G1_GPIO_PuPd                    GPIO_NOPULL
#define MX_LCD_G1                               LTDC_G1
#define MX_LTDC_G1_GPIO_Pin                     GPIO_PIN_8
#define MX_LTDC_G1_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_G1_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PJ9 */
#define MX_LTDC_G2_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_G2_Pin                          PJ9
#define MX_LTDC_G2_GPIOx                        GPIOJ
#define MX_LTDC_G2_GPIO_PuPd                    GPIO_NOPULL
#define MX_LCD_G2                               LTDC_G2
#define MX_LTDC_G2_GPIO_Pin                     GPIO_PIN_9
#define MX_LTDC_G2_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_G2_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PJ7 */
#define MX_LTDC_G0_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_G0_Pin                          PJ7
#define MX_LTDC_G0_GPIOx                        GPIOJ
#define MX_LTDC_G0_GPIO_PuPd                    GPIO_NOPULL
#define MX_LCD_G0                               LTDC_G0
#define MX_LTDC_G0_GPIO_Pin                     GPIO_PIN_7
#define MX_LTDC_G0_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_G0_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PJ5 */
#define MX_LTDC_R6_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_R6_Pin                          PJ5
#define MX_LTDC_R6_GPIOx                        GPIOJ
#define MX_LTDC_R6_GPIO_PuPd                    GPIO_NOPULL
#define MX_LCD_R6                               LTDC_R6
#define MX_LTDC_R6_GPIO_Pin                     GPIO_PIN_5
#define MX_LTDC_R6_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_R6_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PJ6 */
#define MX_LTDC_R7_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_R7_Pin                          PJ6
#define MX_LTDC_R7_GPIOx                        GPIOJ
#define MX_LTDC_R7_GPIO_PuPd                    GPIO_NOPULL
#define MX_LCD_R7                               LTDC_R7
#define MX_LTDC_R7_GPIO_Pin                     GPIO_PIN_6
#define MX_LTDC_R7_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_R7_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PJ3 */
#define MX_LTDC_R4_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_R4_Pin                          PJ3
#define MX_LTDC_R4_GPIOx                        GPIOJ
#define MX_LTDC_R4_GPIO_PuPd                    GPIO_NOPULL
#define MX_LCD_R4                               LTDC_R4
#define MX_LTDC_R4_GPIO_Pin                     GPIO_PIN_3
#define MX_LTDC_R4_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_R4_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PJ4 */
#define MX_LTDC_R5_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_R5_Pin                          PJ4
#define MX_LTDC_R5_GPIOx                        GPIOJ
#define MX_LTDC_R5_GPIO_PuPd                    GPIO_NOPULL
#define MX_LCD_R5                               LTDC_R5
#define MX_LTDC_R5_GPIO_Pin                     GPIO_PIN_4
#define MX_LTDC_R5_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_R5_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PJ1 */
#define MX_LTDC_R2_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_R2_Pin                          PJ1
#define MX_LTDC_R2_GPIOx                        GPIOJ
#define MX_LTDC_R2_GPIO_PuPd                    GPIO_NOPULL
#define MX_LCD_R2                               LTDC_R2
#define MX_LTDC_R2_GPIO_Pin                     GPIO_PIN_1
#define MX_LTDC_R2_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_R2_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PJ2 */
#define MX_LTDC_R3_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_R3_Pin                          PJ2
#define MX_LTDC_R3_GPIOx                        GPIOJ
#define MX_LTDC_R3_GPIO_PuPd                    GPIO_NOPULL
#define MX_LCD_R3                               LTDC_R3
#define MX_LTDC_R3_GPIO_Pin                     GPIO_PIN_2
#define MX_LTDC_R3_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_R3_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PI15 */
#define MX_LTDC_R0_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_R0_Pin                          PI15
#define MX_LTDC_R0_GPIOx                        GPIOI
#define MX_LTDC_R0_GPIO_PuPd                    GPIO_NOPULL
#define MX_LCD_R0                               LTDC_R0
#define MX_LTDC_R0_GPIO_Pin                     GPIO_PIN_15
#define MX_LTDC_R0_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_R0_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PJ0 */
#define MX_LTDC_R1_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_R1_Pin                          PJ0
#define MX_LTDC_R1_GPIOx                        GPIOJ
#define MX_LTDC_R1_GPIO_PuPd                    GPIO_NOPULL
#define MX_LCD_R1                               LTDC_R1
#define MX_LTDC_R1_GPIO_Pin                     GPIO_PIN_0
#define MX_LTDC_R1_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_R1_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PK5 */
#define MX_LTDC_B6_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_B6_Pin                          PK5
#define MX_LTDC_B6_GPIOx                        GPIOK
#define MX_LTDC_B6_GPIO_PuPd                    GPIO_NOPULL
#define MX_LCD_B6                               LTDC_B6
#define MX_LTDC_B6_GPIO_Pin                     GPIO_PIN_5
#define MX_LTDC_B6_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_B6_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PK6 */
#define MX_LTDC_B7_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_B7_Pin                          PK6
#define MX_LTDC_B7_GPIOx                        GPIOK
#define MX_LTDC_B7_GPIO_PuPd                    GPIO_NOPULL
#define MX_LCD_B7                               LTDC_B7
#define MX_LTDC_B7_GPIO_Pin                     GPIO_PIN_6
#define MX_LTDC_B7_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_B7_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PK3 */
#define MX_LTDC_B4_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_B4_Pin                          PK3
#define MX_LTDC_B4_GPIOx                        GPIOK
#define MX_LTDC_B4_GPIO_PuPd                    GPIO_NOPULL
#define MX_LCD_B4                               LTDC_B4
#define MX_LTDC_B4_GPIO_Pin                     GPIO_PIN_3
#define MX_LTDC_B4_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_B4_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PK4 */
#define MX_LTDC_B5_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_B5_Pin                          PK4
#define MX_LTDC_B5_GPIOx                        GPIOK
#define MX_LTDC_B5_GPIO_PuPd                    GPIO_NOPULL
#define MX_LCD_B5                               LTDC_B5
#define MX_LTDC_B5_GPIO_Pin                     GPIO_PIN_4
#define MX_LTDC_B5_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_B5_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PJ14 */
#define MX_LTDC_B2_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_B2_Pin                          PJ14
#define MX_LTDC_B2_GPIOx                        GPIOJ
#define MX_LTDC_B2_GPIO_PuPd                    GPIO_NOPULL
#define MX_LCD_B2                               LTDC_B2
#define MX_LTDC_B2_GPIO_Pin                     GPIO_PIN_14
#define MX_LTDC_B2_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_B2_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PI12 */
#define MX_LTDC_HSYNC_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_LTDC_HSYNC_Pin                       PI12
#define MX_LTDC_HSYNC_GPIOx                     GPIOI
#define MX_LTDC_HSYNC_GPIO_PuPd                 GPIO_NOPULL
#define MX_LCD_HSYNC                            LTDC_HSYNC
#define MX_LTDC_HSYNC_GPIO_Pin                  GPIO_PIN_12
#define MX_LTDC_HSYNC_GPIO_AF                   GPIO_AF14_LTDC
#define MX_LTDC_HSYNC_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PJ15 */
#define MX_LTDC_B3_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_B3_Pin                          PJ15
#define MX_LTDC_B3_GPIOx                        GPIOJ
#define MX_LTDC_B3_GPIO_PuPd                    GPIO_NOPULL
#define MX_LCD_B3                               LTDC_B3
#define MX_LTDC_B3_GPIO_Pin                     GPIO_PIN_15
#define MX_LTDC_B3_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_B3_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PJ12 */
#define MX_LTDC_B0_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_B0_Pin                          PJ12
#define MX_LTDC_B0_GPIOx                        GPIOJ
#define MX_LTDC_B0_GPIO_PuPd                    GPIO_NOPULL
#define MX_LCD_B0                               LTDC_B0
#define MX_LTDC_B0_GPIO_Pin                     GPIO_PIN_12
#define MX_LTDC_B0_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_B0_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PJ13 */
#define MX_LTDC_B1_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_B1_Pin                          PJ13
#define MX_LTDC_B1_GPIOx                        GPIOJ
#define MX_LTDC_B1_GPIO_PuPd                    GPIO_NOPULL
#define MX_LCD_B1                               LTDC_B1
#define MX_LTDC_B1_GPIO_Pin                     GPIO_PIN_13
#define MX_LTDC_B1_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_B1_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PI13 */
#define MX_LTDC_VSYNC_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_LTDC_VSYNC_Pin                       PI13
#define MX_LTDC_VSYNC_GPIOx                     GPIOI
#define MX_LTDC_VSYNC_GPIO_PuPd                 GPIO_NOPULL
#define MX_LCD_VSYNC                            LTDC_VSYNC
#define MX_LTDC_VSYNC_GPIO_Pin                  GPIO_PIN_13
#define MX_LTDC_VSYNC_GPIO_AF                   GPIO_AF14_LTDC
#define MX_LTDC_VSYNC_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PK7 */
#define MX_LTDC_DE_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_LTDC_DE_Pin                          PK7
#define MX_LTDC_DE_GPIOx                        GPIOK
#define MX_LTDC_DE_GPIO_PuPd                    GPIO_NOPULL
#define MX_LCD_DE                               LTDC_DE
#define MX_LTDC_DE_GPIO_Pin                     GPIO_PIN_7
#define MX_LTDC_DE_GPIO_AF                      GPIO_AF14_LTDC
#define MX_LTDC_DE_GPIO_Mode                    GPIO_MODE_AF_PP

/*-------------------------------- OCTOSPI1   --------------------------------*/

#define MX_OCTOSPI1                             1

/* GPIO Configuration */

/* Pin PG6 */
#define MX_OCTOSPIM_P1_NCS_Pin                  PG6
#define MX_OCTOSPIM_P1_NCS_GPIOx                GPIOG
#define MX_OCTOSPIM_P1_NCS_GPIO_PuPd            GPIO_NOPULL
#define MX_OCTOSPIM_P1_NCS_GPIO_Speed_High_Default GPIO_SPEED_FREQ_VERY_HIGH
#define MX_OCSPI1_NCS                           OCTOSPIM_P1_NCS
#define MX_OCTOSPIM_P1_NCS_GPIO_Pin             GPIO_PIN_6
#define MX_OCTOSPIM_P1_NCS_GPIO_AF              GPIO_AF10_OCTOSPIM_P1
#define MX_OCTOSPIM_P1_NCS_GPIO_Mode            GPIO_MODE_AF_PP

/* Pin PC1 */
#define MX_OCTOSPIM_P1_IO4_Pin                  PC1
#define MX_OCTOSPIM_P1_IO4_GPIOx                GPIOC
#define MX_OCTOSPIM_P1_IO4_GPIO_PuPd            GPIO_NOPULL
#define MX_OCTOSPIM_P1_IO4_GPIO_Speed_High_Default GPIO_SPEED_FREQ_VERY_HIGH
#define MX_OCSPI1_IO4                           OCTOSPIM_P1_IO4
#define MX_OCTOSPIM_P1_IO4_GPIO_Pin             GPIO_PIN_1
#define MX_OCTOSPIM_P1_IO4_GPIO_AF              GPIO_AF10_OCTOSPIM_P1
#define MX_OCTOSPIM_P1_IO4_GPIO_Mode            GPIO_MODE_AF_PP

/* Pin PB2 */
#define MX_OCTOSPIM_P1_CLK_Pin                  PB2
#define MX_OCTOSPIM_P1_CLK_GPIOx                GPIOB
#define MX_OCTOSPIM_P1_CLK_GPIO_PuPd            GPIO_NOPULL
#define MX_OCTOSPIM_P1_CLK_GPIO_Speed_High_Default GPIO_SPEED_FREQ_VERY_HIGH
#define MX_OCSPI1_CLK                           OCTOSPIM_P1_CLK
#define MX_OCTOSPIM_P1_CLK_GPIO_Pin             GPIO_PIN_2
#define MX_OCTOSPIM_P1_CLK_GPIO_AF              GPIO_AF9_OCTOSPIM_P1
#define MX_OCTOSPIM_P1_CLK_GPIO_Mode            GPIO_MODE_AF_PP

/* Pin PD7 */
#define MX_OCTOSPIM_P1_IO7_Pin                  PD7
#define MX_OCTOSPIM_P1_IO7_GPIOx                GPIOD
#define MX_OCTOSPIM_P1_IO7_GPIO_PuPd            GPIO_NOPULL
#define MX_OCTOSPIM_P1_IO7_GPIO_Speed_High_Default GPIO_SPEED_FREQ_VERY_HIGH
#define MX_OCSPI1_IO7                           OCTOSPIM_P1_IO7
#define MX_OCTOSPIM_P1_IO7_GPIO_Pin             GPIO_PIN_7
#define MX_OCTOSPIM_P1_IO7_GPIO_AF              GPIO_AF10_OCTOSPIM_P1
#define MX_OCTOSPIM_P1_IO7_GPIO_Mode            GPIO_MODE_AF_PP

/* Pin PG9 */
#define MX_OCTOSPIM_P1_IO6_Pin                  PG9
#define MX_OCTOSPIM_P1_IO6_GPIOx                GPIOG
#define MX_OCTOSPIM_P1_IO6_GPIO_PuPd            GPIO_NOPULL
#define MX_OCTOSPIM_P1_IO6_GPIO_Speed_High_Default GPIO_SPEED_FREQ_VERY_HIGH
#define MX_OCSPI1_IO6                           OCTOSPIM_P1_IO6
#define MX_OCTOSPIM_P1_IO6_GPIO_Pin             GPIO_PIN_9
#define MX_OCTOSPIM_P1_IO6_GPIO_AF              GPIO_AF9_OCTOSPIM_P1
#define MX_OCTOSPIM_P1_IO6_GPIO_Mode            GPIO_MODE_AF_PP

/* Pin PH3 */
#define MX_OCTOSPIM_P1_IO5_Pin                  PH3
#define MX_OCTOSPIM_P1_IO5_GPIOx                GPIOH
#define MX_OCTOSPIM_P1_IO5_GPIO_PuPd            GPIO_NOPULL
#define MX_OCTOSPIM_P1_IO5_GPIO_Speed_High_Default GPIO_SPEED_FREQ_VERY_HIGH
#define MX_OCSPI1_IO5                           OCTOSPIM_P1_IO5
#define MX_OCTOSPIM_P1_IO5_GPIO_Pin             GPIO_PIN_3
#define MX_OCTOSPIM_P1_IO5_GPIO_AF              GPIO_AF9_OCTOSPIM_P1
#define MX_OCTOSPIM_P1_IO5_GPIO_Mode            GPIO_MODE_AF_PP

/* Pin PC5 */
#define MX_OCTOSPIM_P1_DQS_Pin                  PC5
#define MX_OCTOSPIM_P1_DQS_GPIOx                GPIOC
#define MX_OCTOSPIM_P1_DQS_GPIO_PuPd            GPIO_NOPULL
#define MX_OCTOSPIM_P1_DQS_GPIO_Speed_High_Default GPIO_SPEED_FREQ_VERY_HIGH
#define MX_OCSPI1_DQS                           OCTOSPIM_P1_DQS
#define MX_OCTOSPIM_P1_DQS_GPIO_Pin             GPIO_PIN_5
#define MX_OCTOSPIM_P1_DQS_GPIO_AF              GPIO_AF10_OCTOSPIM_P1
#define MX_OCTOSPIM_P1_DQS_GPIO_Mode            GPIO_MODE_AF_PP

/*-------------------------------- RTC        --------------------------------*/

#define MX_RTC                                  1

/* GPIO Configuration */

/*-------------------------------- SDMMC1     --------------------------------*/

#define MX_SDMMC1                               1

/* GPIO Configuration */

/* Pin PD2 */
#define MX_SDMMC1_CMD_Pin                       PD2
#define MX_SDMMC1_CMD_GPIOx                     GPIOD
#define MX_SDMMC1_CMD_GPIO_PuPd                 GPIO_NOPULL
#define MX_SDMMC1_CMD_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDIO1_CMD                            SDMMC1_CMD
#define MX_SDMMC1_CMD_GPIO_Pin                  GPIO_PIN_2
#define MX_SDMMC1_CMD_GPIO_AF                   GPIO_AF12_SDMMC1
#define MX_SDMMC1_CMD_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PC8 */
#define MX_SDMMC1_D0_Pin                        PC8
#define MX_SDMMC1_D0_GPIOx                      GPIOC
#define MX_SDMMC1_D0_GPIO_PuPd                  GPIO_NOPULL
#define MX_SDMMC1_D0_GPIO_Speed_High_Default    GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDIO1_D0                             SDMMC1_D0
#define MX_SDMMC1_D0_GPIO_Pin                   GPIO_PIN_8
#define MX_SDMMC1_D0_GPIO_AF                    GPIO_AF12_SDMMC1
#define MX_SDMMC1_D0_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PC9 */
#define MX_SDMMC1_D1_Pin                        PC9
#define MX_SDMMC1_D1_GPIOx                      GPIOC
#define MX_SDMMC1_D1_GPIO_PuPd                  GPIO_NOPULL
#define MX_SDMMC1_D1_GPIO_Speed_High_Default    GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDIO1_D1                             SDMMC1_D1
#define MX_SDMMC1_D1_GPIO_Pin                   GPIO_PIN_9
#define MX_SDMMC1_D1_GPIO_AF                    GPIO_AF12_SDMMC1
#define MX_SDMMC1_D1_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PC10 */
#define MX_SDMMC1_D2_Pin                        PC10
#define MX_SDMMC1_D2_GPIOx                      GPIOC
#define MX_SDMMC1_D2_GPIO_PuPd                  GPIO_NOPULL
#define MX_SDMMC1_D2_GPIO_Speed_High_Default    GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDIO1_D2                             SDMMC1_D2
#define MX_SDMMC1_D2_GPIO_Pin                   GPIO_PIN_10
#define MX_SDMMC1_D2_GPIO_AF                    GPIO_AF12_SDMMC1
#define MX_SDMMC1_D2_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PC11 */
#define MX_SDMMC1_D3_Pin                        PC11
#define MX_SDMMC1_D3_GPIOx                      GPIOC
#define MX_SDMMC1_D3_GPIO_PuPd                  GPIO_NOPULL
#define MX_SDMMC1_D3_GPIO_Speed_High_Default    GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDIO1_D3                             SDMMC1_D3
#define MX_SDMMC1_D3_GPIO_Pin                   GPIO_PIN_11
#define MX_SDMMC1_D3_GPIO_AF                    GPIO_AF12_SDMMC1
#define MX_SDMMC1_D3_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PC12 */
#define MX_SDMMC1_CK_Pin                        PC12
#define MX_SDMMC1_CK_GPIOx                      GPIOC
#define MX_SDMMC1_CK_GPIO_PuPd                  GPIO_NOPULL
#define MX_SDMMC1_CK_GPIO_Speed_High_Default    GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDIO1_CK                             SDMMC1_CK
#define MX_SDMMC1_CK_GPIO_Pin                   GPIO_PIN_12
#define MX_SDMMC1_CK_GPIO_AF                    GPIO_AF12_SDMMC1
#define MX_SDMMC1_CK_GPIO_Mode                  GPIO_MODE_AF_PP

/* NVIC Configuration */

/* NVIC SDMMC1_IRQn */
#define MX_SDMMC1_IRQn_interruptPremptionPriority 8
#define MX_SDMMC1_IRQn_PriorityGroup            NVIC_PRIORITYGROUP_4
#define MX_SDMMC1_IRQn_Subriority               0

/*-------------------------------- SPI2       --------------------------------*/

#define MX_SPI2                                 1

/* GPIO Configuration */

/* Pin PA12 */
#define MX_SPI2_SCK_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_SPI2_SCK_Pin                         PA12
#define MX_SPI2_SCK_GPIOx                       GPIOA
#define MX_SPI2_SCK_GPIO_PuPd                   GPIO_NOPULL
#define MX_SPI2_SCK                             SPI2_SCK
#define MX_SPI2_SCK_GPIO_Pin                    GPIO_PIN_12
#define MX_SPI2_SCK_GPIO_AF                     GPIO_AF5_SPI2
#define MX_SPI2_SCK_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PC2 */
#define MX_SPI2_MISO_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_SPI2_MISO_Pin                        PC2
#define MX_SPI2_MISO_GPIOx                      GPIOC
#define MX_SPI2_MISO_GPIO_PuPd                  GPIO_NOPULL
#define MX_SPI2_MISO                            SPI2_MISO
#define MX_SPI2_MISO_GPIO_Pin                   GPIO_PIN_2
#define MX_SPI2_MISO_GPIO_AF                    GPIO_AF5_SPI2
#define MX_SPI2_MISO_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PC3 */
#define MX_SPI2_MOSI_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_SPI2_MOSI_Pin                        PC3
#define MX_SPI2_MOSI_GPIOx                      GPIOC
#define MX_SPI2_MOSI_GPIO_PuPd                  GPIO_NOPULL
#define MX_SPI2_MOSI                            SPI2_MOSI
#define MX_SPI2_MOSI_GPIO_Pin                   GPIO_PIN_3
#define MX_SPI2_MOSI_GPIO_AF                    GPIO_AF5_SPI2
#define MX_SPI2_MOSI_GPIO_Mode                  GPIO_MODE_AF_PP

/* DMA Configuration */

/* DMA SPI2_TX */
#define MX_SPI2_TX_DMA_Instance                 DMA1_Stream1
#define MX_SPI2_TX_DMA_FIFOMode                 DMA_FIFOMODE_DISABLE
#define MX_SPI2_TX_DMA_Priority                 DMA_PRIORITY_LOW
#define MX_SPI2_TX_DMA_MemDataAlignment         DMA_MDATAALIGN_BYTE
#define MX_SPI2_TX_DMA_Mode                     DMA_NORMAL
#define MX_SPI2_TX_DMA_SyncRequestNumber        1
#define MX_SPI2_TX_DMA_Request                  DMA_REQUEST_SPI2_TX
#define MX_SPI2_TX_DMA_SyncPolarity             HAL_DMAMUX_SYNC_NO_EVENT
#define MX_SPI2_TX_DMA_Direction                DMA_MEMORY_TO_PERIPH
#define MX_SPI2_TX_DMA_SignalID                 NONE
#define MX_SPI2_TX_DMA_MemInc                   DMA_MINC_ENABLE
#define MX_SPI2_TX_DMA_IpInstance
#define MX_SPI2_TX_DMA_RequestNumber            1
#define MX_SPI2_TX_DMA_EventEnable              DISABLE
#define MX_SPI2_TX_DMA_SyncEnable               DISABLE
#define MX_SPI2_TX_DMA_DMA_Handle
#define MX_SPI2_TX_DMA_PeriphDataAlignment      DMA_PDATAALIGN_BYTE
#define MX_SPI2_TX_DMA_Polarity                 HAL_DMAMUX_REQ_GEN_RISING
#define MX_SPI2_TX_DMA_SyncSignalID             NONE
#define MX_SPI2_TX_DMA_PeriphInc                DMA_PINC_DISABLE

/* DMA SPI2_RX */
#define MX_SPI2_RX_DMA_Instance                 DMA1_Stream0
#define MX_SPI2_RX_DMA_FIFOMode                 DMA_FIFOMODE_DISABLE
#define MX_SPI2_RX_DMA_Priority                 DMA_PRIORITY_LOW
#define MX_SPI2_RX_DMA_MemDataAlignment         DMA_MDATAALIGN_BYTE
#define MX_SPI2_RX_DMA_Mode                     DMA_NORMAL
#define MX_SPI2_RX_DMA_SyncRequestNumber        1
#define MX_SPI2_RX_DMA_Request                  DMA_REQUEST_SPI2_RX
#define MX_SPI2_RX_DMA_SyncPolarity             HAL_DMAMUX_SYNC_NO_EVENT
#define MX_SPI2_RX_DMA_Direction                DMA_PERIPH_TO_MEMORY
#define MX_SPI2_RX_DMA_SignalID                 NONE
#define MX_SPI2_RX_DMA_MemInc                   DMA_MINC_ENABLE
#define MX_SPI2_RX_DMA_IpInstance
#define MX_SPI2_RX_DMA_RequestNumber            1
#define MX_SPI2_RX_DMA_EventEnable              DISABLE
#define MX_SPI2_RX_DMA_SyncEnable               DISABLE
#define MX_SPI2_RX_DMA_DMA_Handle
#define MX_SPI2_RX_DMA_PeriphDataAlignment      DMA_PDATAALIGN_BYTE
#define MX_SPI2_RX_DMA_Polarity                 HAL_DMAMUX_REQ_GEN_RISING
#define MX_SPI2_RX_DMA_SyncSignalID             NONE
#define MX_SPI2_RX_DMA_PeriphInc                DMA_PINC_DISABLE

/* NVIC Configuration */

/* NVIC SPI2_IRQn */
#define MX_SPI2_IRQn_interruptPremptionPriority 8
#define MX_SPI2_IRQn_PriorityGroup              NVIC_PRIORITYGROUP_4
#define MX_SPI2_IRQn_Subriority                 0

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/*-------------------------------- TIM2       --------------------------------*/

#define MX_TIM2                                 1

/* GPIO Configuration */

/*-------------------------------- UART4      --------------------------------*/

#define MX_UART4                                1

#define MX_UART4_VM                             VM_ASYNC

/* GPIO Configuration */

/* Pin PH14 */
#define MX_UART4_RX_GPIO_ModeDefaultPP          GPIO_MODE_AF_PP
#define MX_UART4_RX_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_UART4_RX_Pin                         PH14
#define MX_UART4_RX_GPIOx                       GPIOH
#define MX_UART4_RX_GPIO_PuPd                   GPIO_NOPULL
#define MX_UART4_RX_GPIO_Pin                    GPIO_PIN_14
#define MX_UART4_RX_GPIO_AF                     GPIO_AF8_UART4

/* Pin PH13 */
#define MX_UART4_TX_GPIO_ModeDefaultPP          GPIO_MODE_AF_PP
#define MX_UART4_TX_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_UART4_TX_Pin                         PH13
#define MX_UART4_TX_GPIOx                       GPIOH
#define MX_UART4_TX_GPIO_PuPd                   GPIO_NOPULL
#define MX_UART4_TX_GPIO_Pin                    GPIO_PIN_13
#define MX_UART4_TX_GPIO_AF                     GPIO_AF8_UART4

/* NVIC Configuration */

/* NVIC UART4_IRQn */
#define MX_UART4_IRQn_interruptPremptionPriority 8
#define MX_UART4_IRQn_PriorityGroup             NVIC_PRIORITYGROUP_4
#define MX_UART4_IRQn_Subriority                0

/*-------------------------------- USART1     --------------------------------*/

#define MX_USART1                               1

#define MX_USART1_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PA9 */
#define MX_USART1_TX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART1_TX_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_USART1_TX_Pin                        PA9
#define MX_USART1_TX_GPIOx                      GPIOA
#define MX_USART1_TX_GPIO_PuPd                  GPIO_NOPULL
#define MX_VCP_TX                               USART1_TX
#define MX_USART1_TX_GPIO_Pin                   GPIO_PIN_9
#define MX_USART1_TX_GPIO_AF                    GPIO_AF7_USART1

/* Pin PA10 */
#define MX_USART1_RX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART1_RX_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_USART1_RX_Pin                        PA10
#define MX_USART1_RX_GPIOx                      GPIOA
#define MX_USART1_RX_GPIO_PuPd                  GPIO_NOPULL
#define MX_VCP_RX                               USART1_RX
#define MX_USART1_RX_GPIO_Pin                   GPIO_PIN_10
#define MX_USART1_RX_GPIO_AF                    GPIO_AF7_USART1

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PA2 */
#define MX_PA2_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PA2_Pin                              PA2
#define MX_PA2_GPIOx                            GPIOA
#define MX_PA2_PinState                         GPIO_PIN_SET
#define MX_PA2_GPIO_PuPd                        GPIO_NOPULL
#define MX_LCD_ON_OFF                           PA2
#define MX_PA2_GPIO_Pin                         GPIO_PIN_2
#define MX_PA2_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PA1 */
#define MX_PA1_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PA1_Pin                              PA1
#define MX_PA1_GPIOx                            GPIOA
#define MX_PA1_PinState                         GPIO_PIN_SET
#define MX_PA1_GPIO_PuPd                        GPIO_NOPULL
#define MX_LCD_BL_CTRL                          PA1
#define MX_PA1_GPIO_Pin                         GPIO_PIN_1
#define MX_PA1_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PC13 */
#define MX_PC13_Pin                             PC13
#define MX_PC13_GPIOx                           GPIOC
#define MX_PC13_GPIO_PuPd                       GPIO_NOPULL
#define MX_WAKEUP                               PC13
#define MX_PC13_GPIO_Pin                        GPIO_PIN_13
#define MX_PC13_GPIO_ModeDefaultEXTI            GPIO_MODE_IT_RISING

/* Pin PG11 */
#define MX_PG11_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PG11_Pin                             PG11
#define MX_PG11_GPIOx                           GPIOG
#define MX_PG11_PinState                        GPIO_PIN_RESET
#define MX_PG11_GPIO_PuPd                       GPIO_NOPULL
#define MX_USER_LED1                            PG11
#define MX_PG11_GPIO_Pin                        GPIO_PIN_11
#define MX_PG11_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PA11 */
#define MX_PA11_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PA11_Pin                             PA11
#define MX_PA11_GPIOx                           GPIOA
#define MX_PA11_PinState                        GPIO_PIN_RESET
#define MX_PA11_GPIO_PuPd                       GPIO_NOPULL
#define MX_SPI2_NSS                             PA11
#define MX_PA11_GPIO_Pin                        GPIO_PIN_11
#define MX_PA11_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PI2 */
#define MX_PI2_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PI2_Pin                              PI2
#define MX_PI2_GPIOx                            GPIOI
#define MX_PI2_PinState                         GPIO_PIN_RESET
#define MX_PI2_GPIO_PuPd                        GPIO_NOPULL
#define MX_WIFI_WKUP                            PI2
#define MX_PI2_GPIO_Pin                         GPIO_PIN_2
#define MX_PI2_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PI1 */
#define MX_PI1_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PI1_Pin                              PI1
#define MX_PI1_GPIOx                            GPIOI
#define MX_PI1_PinState                         GPIO_PIN_RESET
#define MX_PI1_GPIO_PuPd                        GPIO_NOPULL
#define MX_WIFI_RST                             PI1
#define MX_PI1_GPIO_Pin                         GPIO_PIN_1
#define MX_PI1_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PI4 */
#define MX_PI4_Pin                              PI4
#define MX_PI4_GPIOx                            GPIOI
#define MX_PI4_GPIO_PuPd                        GPIO_NOPULL
#define MX_WIFI_GPIO                            PI4
#define MX_PI4_GPIO_Pin                         GPIO_PIN_4
#define MX_PI4_GPIO_ModeDefaultEXTI             GPIO_MODE_IT_RISING

/* Pin PG2 */
#define MX_PG2_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PG2_Pin                              PG2
#define MX_PG2_GPIOx                            GPIOG
#define MX_PG2_PinState                         GPIO_PIN_RESET
#define MX_PG2_GPIO_PuPd                        GPIO_NOPULL
#define MX_USER_LED2                            PG2
#define MX_PG2_GPIO_Pin                         GPIO_PIN_2
#define MX_PG2_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PI3 */
#define MX_PI3_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PI3_Pin                              PI3
#define MX_PI3_GPIOx                            GPIOI
#define MX_PI3_PinState                         GPIO_PIN_RESET
#define MX_PI3_GPIO_PuPd                        GPIO_NOPULL
#define MX_WIFI_BOOT                            PI3
#define MX_PI3_GPIO_Pin                         GPIO_PIN_3
#define MX_PI3_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PH2 */
#define MX_PH2_Pin                              PH2
#define MX_PH2_GPIOx                            GPIOH
#define MX_PH2_GPIO_PuPd                        GPIO_NOPULL
#define MX_LCD_INT                              PH2
#define MX_PH2_GPIO_Pin                         GPIO_PIN_2
#define MX_PH2_GPIO_ModeDefaultEXTI             GPIO_MODE_IT_RISING

/* Pin PI5 */
#define MX_PI5_Pin                              PI5
#define MX_PI5_GPIOx                            GPIOI
#define MX_PI5_GPIO_PuPd                        GPIO_NOPULL
#define MX_WIFI_DATRDY                          PI5
#define MX_PI5_GPIO_Pin                         GPIO_PIN_5
#define MX_PI5_GPIO_ModeDefaultEXTI             GPIO_MODE_IT_RISING

/* Pin PG3 */
#define MX_PG3_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PG3_Pin                              PG3
#define MX_PG3_GPIOx                            GPIOG
#define MX_PG3_PinState                         GPIO_PIN_SET
#define MX_PG3_GPIO_PuPd                        GPIO_NOPULL
#define MX_AUDIO_NRST                           PG3
#define MX_PG3_GPIO_Pin                         GPIO_PIN_3
#define MX_PG3_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PI8 */
#define MX_PI8_Pin                              PI8
#define MX_PI8_GPIOx                            GPIOI
#define MX_PI8_GPIO_PuPd                        GPIO_PULLUP
#define MX_uSD_Detect                           PI8
#define MX_PI8_GPIO_Pin                         GPIO_PIN_8
#define MX_PI8_GPIO_ModeDefaultEXTI             GPIO_MODE_IT_RISING

#endif  /* __MX_DEVICE_H */

