# yaml-language-server: $schema=https://raw.githubusercontent.com/Open-CMSIS-Pack/devtools/schemas/projmgr/0.9.0/tools/projmgr/schemas/csolution.schema.json

solution:

  target-types:
    - type: EVKB_IMXRT1050_ESP8266
      # board: EVKB-IMXRT1050_MDK
      device: MIMXRT1052DVL6B
    - type: EVKB_IMXRT1050_WizFi360
      # board: EVKB-IMXRT1050_MDK
      device: MIMXRT1052DVL6B
    # - type: EVKB_IMXRT1050_FreeRTOS_TCP
    #   # board: EVKB-IMXRT1050_MDK
    #   device: MIMXRT1052DVL6B
    - type: EVKB_IMXRT1050_MW-Network_ETH
      # board: EVKB-IMXRT1050_MDK
      device: MIMXRT1052DVL6B
    # - type: EVKB_IMXRT1050_lwIP_ETH
    #   # board: EVKB-IMXRT1050_MDK
    #   device: MIMXRT1052DVL6B

    - type: VHT_CM7_VSocket
      device: ARM::CMSDK_CM7_DP_VHT
    # - type: VHT_CM7_FreeRTOS_TCP
    #   device: ARM::CMSDK_CM7_DP_VHT
    - type: VHT_CM7_MW-Network_ETH
      device: ARM::CMSDK_CM7_DP_VHT
    # - type: VHT_CM7_lwIP_ETH
    #   device: ARM::CMSDK_CM7_DP_VHT

  build-types:
    - type: Debug
      compiler: AC6
      misc:
        - C*:
          - -O1
          - -g
    - type: Release
      compiler: AC6
      misc:
        - C*:
          - -O3

  projects:
    - project: ./AWS_MQTT_MutualAuth_Demo.cproject.yml
